name: 'Set up a Rust toolchain'
description: 'Install a specific Rust toolchain and add it to the PATH'
author: 'Héctor Ramón'
inputs:
  rust-version:
    description: 'The toolchain name, such as stable, nightly, or 1.8.0'
    default: 'stable'
  components:
    description: 'The toolchain components to install, comma-separated'
    default: ''
  targets:
    description: 'The toolchain targets to add, comma-separated'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'download'
  color: 'blue'
